name: "domain_adapter"
platform: "onnxruntime_onnx"
optimization {
    execution_accelerators {
        gpu_execution_accelerator : [ {
            name : "tensorrt"
            parameters { key: "precision_mode" value: "FP16" }
        }]
    }
    cuda { graphs: 0 }
}
instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus: [ 0 ]
    }
]